# Generated by Django 6.0.7 on 2026-07-29 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_nuber',
            new_name='phone_number',
        ),
    ]
